#!/usr/bin/env bash
#MISE description="Run linters"
set -euo pipefail

UNFORMATTED=$(gofmt -l .)
if [ -n "$UNFORMATTED" ]; then
  echo "Unformatted files:"
  echo "$UNFORMATTED"
  exit 1
fi

go vet ./...
golangci-lint run ./...
